# Foraward simulation for sandbox

In [ ]:
import os
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# from sleio import select_node

ImportError: cannot import name 'select_node' from 'sleio' (c:\Users\a0980\Desktop\Ethan\Sandbox\HTNN_Sandbox\sleio.py)

## test

In [ ]:
ele = np.tile([4], (1, 1))
floor = np.tile([0, " "], (5, 1))
print(ele)

In [ ]:
df_floor = pd.DataFrame(np.tile([0, " "], (5, 1)))
# df_num = pd.DataFrame(np.array([4, " "]))
df_floor

In [2]:
cor = (
    (1, 5),
    (2, 3)
)

for i in range(len(cor)):
    x, y = cor[i]
    print(x)

1
2

In [35]:
def fake_return(coords):
    
    fake = []
    for coord in coords:
        
        
        x, y, z = coord
        value = np.sum(np.array([x, y, z]))
        
        fake.append(value)
    
    return pd.DataFrame({'node_id':fake[:]})

node_ids = fake_return(  ((288.5, 101, 150) , (288.5, 101, 150))  )
node_ids.values

array([[539.5],
       [539.5]])

In [36]:
# try 2 stress
# first stress with 2 inj well
# second stress with 1 inj well
# srcs = (
#    (stress 1)
#    (stress 2)
# )
#         
srcs = ( 
        ( ((288.5, 101, 150) , (288.5, 101, 150)), ('inj_1', 'inj_2'), ((0, 12), (0, 36)), (200, 300)),     
        ( ((300.5, 125, 150)) , ('inj_3'), ((0, 24)), (600)) 
    )

# 每一個 stress
for src in srcs:
    
    coords, inj_names, time, inj_ints =  src
    print(coords)
    
    well_number = len(coords)
    node_ids = fake_return(coords)
    
    print(well_number)
    # 一個stress中 每一個井
    # l = []
    # for i in range(well_number):
        
    #     info_line = np.array(node_ids[i], inj_ints[i], 0, time[i][0], time[i][1], inj_names[i])
        
    #     l.append(info_line)

    # df = pd.DataFrame( {l})
    
    # pd.concat()

# return pd.concat(df1, df2) 



# fake = fake_return(((288.5, 101, 150) , (288.5, 101, 150)))
# print(fake.values)

((288.5, 101, 150), (288.5, 101, 150))
2
(300.5, 125, 150)

TypeError: cannot unpack non-iterable float object

In [ ]:
# for bc
df_bc = pd.DataFrame({
    'node_id':  node_id_select,
    'init_h': self.init_paras[0],
    'flux':   self.init_paras[1],
    'sc': 0,  
    'sflux': 0
})

In [8]:
df = pd.DataFrame(
    
    {'x': [1, 2, 3],
     'y': [4, 5, 6],
     'z': [10, 10,20]
    },
)


df.iloc[:, :2]

   x  y
0  1  4
1  2  5
2  3  6

In [21]:
c_1 = (df['x'] == 1)
c_2 = (df['z'] == 10)



l = [c_1, c_2]
l[1]


pd.DataFrame(
    {
        'a': [1, 2, 3],
        'b': 0
        
    }
)

   a  b
0  1  0
1  2  0
2  3  0

## Simulation control

In [ ]:
# simulation control
# CREATE OUTPUT?
# FLOW TYPE?
# INITIAL HEAD TYPE? 
project_name = 'test_0701'
simulation_control = ('3D', 'steady', 'confined')  # dimension, problem, aquifer

simu_list = [2, 2, 1, 50, 0.5, 0.5, 0.001, 10e-10, 10e-10, 10e-10]


# Geometry control
dx = np.array( [43.5, 25, 20, 20, 20] + [7.5] * 19 + [6, 6, 5.5, 5.5, 6, 6] + [7.5] * 19 + [20, 20, 20, 25, 43.5])
dy = np.array( [31, 20, 20, 20, 10] + [7.5] * 24 + [10, 20, 20, 20, 31])
dz = np.array( [30, 25, 20, 15, 10, 10] + [5] * 11 + [7.5, 7.5] + [10, 10, 10, 25, 30, 35] )

start_coord = (0, 0, 0)         # origin coordinate (x0, y0, z0)
element_num = (54, 34, 25)      # element number in each direction (e_x, e_y, e_z)
element_spacing = (dx, dy, dz)  # element spacing in each direction (len(dx) = e_x-)

# initial condition
init_paras = (1.71, 0, 0.0001, 0.00001, 0.4) # init_h, init_flux, init_K, init_Ss, porosity

# boundary condition
boundary = ('Surface', 'UP')  # method, value

# stimulus sources

src_wells = ( ((288.5, 101, 150), 'inj', 600) )    # ( w1, w2, ...) 
                                                   # w1 = ((x, y), 'well name', inj_intensity)) 

# time info for transient
time_list = ( (10, 10, 1, 600, 2, 0)  )            # ( w1, w2, ...) 
                                                   # w1 = (dt, dt_max, dt_mul, t_max, _, _)

# observation well
obs_wells = ( ((288.5, 101, 150), 'ob1') )         # ( w1, w2, ...) 
                                                   # w1 = ((x, y), 'well name'))  

# write forward files
wirting_dir = ''
test_forward = sle_io(project_name)
test_forward.set_parameters(simulation_control)
test_forward.add_geometry(start_coord, element_num, element_spacing)
test_forward.add_initial(init_paras)

Project: test_0701
Simulation with '3D' case, 'confined' aquifer under 'steady' state

In [ ]:
# simulation control
project_name = 'test_0701'
simulation_control = ('3D', 'confined', 'steady')  # dimension, aquifer_type, simulation state

# Geometry info
start_coord = (0, 0, 0)
element_list = (54, 34, 25) # ele_num_x, ele_num_y, ele_num_z  ! 建立防呆，多少個element提供多少個dx 需要的欄位

dx = np.array( [43.5, 25, 20, 20, 20] + [7.5] * 19 + [6, 6, 5.5, 5.5, 6, 6] + [7.5] * 19 + [20, 20, 20, 25, 43.5])
dy = np.array( [31, 20, 20, 20, 10] + [7.5] * 24 + [10, 20, 20, 20, 31])
dz = np.array( [30, 25, 20, 15, 10, 10] + [5] * 12 + [7.5, 7.5] + [10, 10, 10, 25, 30, 35] )
element_spacing = (dx, dy, dz)

# initial data
init_para = (1.71, 0.0001, 0.00001, 0.4) # init_h, init_K, init_Ss, porosity

# aquifer type
aquifer_type = 0 # confined

# boundary  ! 建立可以包含"點" 以及"面"的邊界條件寫入方法
boundary_node = [

    [2    , 0.875, init_h],
    [1.875, 0.75 , init_h],
    [2.125, 0.75,  init_h],
    [1.875, 0.625, init_h],
    [2    , 0.625, init_h],
    [2.125, 0.625, init_h],  
    [1.75, 0.625,  init_h],  
    [2    , 0.5,   init_h],
]



# obwell ! 建立防呆，一樣多少個obs_num要輸入多少的觀測井資訊
w1 = [922,  'w1']
w2 = [3308, 'w2']
w3 = [4506, 'w3']
w4 = [3410, 'w4']
w5 = [2234, 'w5']
w6 = [4702, 'w6']
w7 = [2336, 'w7']
w8 = [1158, 'w8']
wm = [3416, 'wm']

# sources
t_start, t_end = [0, 600] 
well_name = ['w1', 'w2', 'w3', 'w4', 'w5', 'w6', 'w7', 'w8', 'wm'] 
inj_intensity = np.array([
                        1.55, # w1
                        1.50, ## w2
                        1.50, ## w3
                        1.49, ## w4
                        1.54, ## w5
                        1.33, ## w6
                        1.39, ## w7
                        1.44, ## w8  
                        1.54  ## wm
                        ])


# create forward files  ! 此處將搭配sleio.write_forward_input() 並劃出網格圖
for i , well in enumerate(well_name): 
    os.chdir(os.path.join(work_dir, proj_name, 'forward'))
    try:
        os.mkdir(well)  
    except:
        pass

    os.chdir(well) 
    src_1 =  [pump_node[i], inj_intensity[i], t_start, t_end, well]
    src_list = [ 
        [src_1] 
    ]
        
    sle_forward = sleio(f'3d_yongjhen_demo_{well}_injection')
    sle_forward.grid_element(element_list)
    sle_forward.node(start_coord = start_coord , element_spacing=[dx, dy, dz], init_h = init_h)
    sle_forward.material(init_K, init_Ss, porosity = porosity)
    sle_forward.sources(src_list)
    sle_forward.boundary_node(boundary_node, 1, init_h)
    sle_forward.obwell([ob_list[i]])
    sle_forward.function(aquifer_type)
    time_list = [[10, 10, 1, 600, 2, 0]] # dt, dt_max, dt_mul, t_max, ...
    prob_list = [1, 1, 1, 1, 1]            # forward(1)/inverse(0), create output.dat, transient(2)/steady(1), ...
    simu_list = [2, 2, 1, 50, 0.5, 0.5, 0.001, 10e-10, 10e-10, 10e-10]
    sle_forward.time(time_list)
    sle_forward.simulation(prob_list, simu_list, plot_domain=True)
    sle_forward.write_forward_input(os.getcwd())

## test forward simulation

In [ ]:
#%% test forward simulation (try previous sle result)
# os.chdir(os.path.join(proj_dir, 'inverse_after_clogging'))
# df_result_lnK_mean, df_result_lnK_var = parse_estimation('O-kestimate.dat', dim =3)
os.chdir(os.path.join(proj_dir, 'inverse'))
df_result = pd.read_csv('HTNN_result.csv')

test_list = []
for i , well in enumerate(well_name): 
    os.chdir(os.path.join(work_dir, proj_name, 'forward', well))
    sle_forward_htnn = sleio(f'test_forward with {well} injection')
    k_est =  np.exp(df_result['HTNN_after_clogging'].values)
    df = sle_forward_htnn.run_forward( k_est, 0.00025, 'steady', init_h , plot_head = False)
    test_list.append(df.values[0])
simulation_head = np.concatenate(test_list, axis = 0)
# print(simulation_head.shape)